### ISSUE TITLE
══ Exception caught by widgets library ══ _TreeDesignPageState.dispose failed to call super.dispose.

### ISSUE THREAD

**Issue by devCLee** [Solved-Earth/Solved.Earth#1]
[Image of the occurred exception](https://i.stack.imgur.com/xSRKc.png)

https://stackoverflow.com/questions/76771040/exception-caught-by-widgets-library-treedesignpagestate-dispose-failed-to-call

https://velog.io/@chanhook/The-following-assertion-was-thrown-while-finalizing-the-widget-treeFindIdState.dispose-failed-to-call-super.dispose

https://www.geeksforgeeks.org/flutter-dispose-method-with-example/

Exception has occurred.
FlutterError (_TreeDesignPageState.dispose failed to call super.dispose.
dispose() implementations must always call their superclass dispose() method, to ensure that all the resources used by the widget are fully released.)

# tree_design_page.dart
```
//...//

class _TreeDesignPageState extends State<TreeDesignPage> with ChangeNotifier {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        constraints: const BoxConstraints.expand(),
        decoration: const BoxDecoration(
          image: DecorationImage(
            image: AssetImage('images/landscape1.jpg'), //the background image
            fit: BoxFit.cover,
          ),
        ),
        child: PageView.builder(
          itemCount: treeModelList.length,
          itemBuilder: (context, index) {
            return Stack(
              children: [
                InkWell(
                  onTap: () {
                    print("Clicked ${treeModelList[index].id}!");
                    selectedtreeindex = index;
                    notifyListeners();
                  }, //Expected to be the point where the error occurs
                  //...//
                ),
                //...//
              ],
            );
          },
        ),
      ),
    );
  }
}
```

**Comment by devCLee** [comment]
Implement 'StreamProvider.autoDispose'

Or at least it should be solved by using Riverpod maybe...

**Comment by jsjin7371** [comment]
이 오류는 트리 디자인 페이지에서 
```
onTap: () {
                    showSnackBar(
                        "${treeModelList[index].id}번째 나무로 변경되었습니다!", context);
                    //print("Clicked ${treeModelList[index].id}!");
                    selectedtreeindex = index;
                    notifyListeners();
                 },
``` 
에서 발생함.

이 오류는 위젯이 불필요하게 여러 번 생성되어 발생한 것으로 추측함.

따라서 notifyListeners(); 함수를 삭제해 위젯이 여러 번 생성되는 것을 막고, 
클래스의 형태를 with ChangeNotifier로 확장하는 것도 삭제하였다.

또한 위젯의 적절한 파기를 위해 다음과 같은 함수를 추가하였다.
```
@override
  void dispose() {
    super.dispose();
  }
 ```
위 내용이 정확한 이유인지는 모르겠음. 뭔가 뭔가 오류가 발생한 원인은 감이 잡히는데 정확한 이유를 모르겠음...ㅠ
