### ISSUE TITLE
'_File' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by devCLee** [Solved-Earth/Solved.Earth#10]
An error occurred while posting an image to the API

**Comment by jsjin7371** [comment]
if you look at the definition of post (in var response = await http.post).

/// [body] sets the body of the request. It can be a [String], a [List<int>] or
/// a [Map<String, String>]. If it's a String, it's encoded using [encoding] and
/// used as the body of the request. The content-type of the request will
/// default to "text/plain".

**so it must be send as [String] , [List<int>] or [Map<String, String>]**

but 
 var response = await http.post(uri, body: {
      'image': File.fromRawPath(file), 
    });

you send it as file format

**Comment by jsjin7371** [comment]
to send image you have two option (maybe more, but i'm idiot)

**1. using MultipartRequest**
var request = http.MultipartRequest('POST', uri)
      ..files.add(http.MultipartFile(
        'image', // File field name
        Stream.fromIterable(file.map(
            (int byte) => [byte])), // Convert Uint8List to Stream<List<int>>
        file.length, // Length of the Uint8List
      ));
      
 **2. convert Uint8List to base64**
 var response = await http.post(uri, body: {
  'image': base64Encode(file), // convert Uint8List to base64
});
in this case, sever have to decode the base64 (I think?)
